services:
  fastapi:
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    container_name: hustleflow-fastapi
    ports:
      - "8000:8000"
    networks:
      - hustleflow-net

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB_DEV}
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - hustleflow-net

  be:
    build:
      context: ./app
    container_name: hustleflow-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB_DEV}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER_DEV}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      ML_SERVICE_BASE_URL: http://fastapi:8000
    depends_on:
      fastapi:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - hustleflow-net

volumes:
  pgdata:

networks:
  hustleflow-net:
    driver: bridge
