spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB_DEV}
spring.datasource.username=${POSTGRES_USER_DEV}
spring.datasource.password=${POSTGRES_PASSWORD_DEV}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=749f6c5add25c1d5f1fdfcad84e72c76650a0d775d3c73484195de014d9a0e23
jwt.expiration=3600000

logging.level.root=DEBUG
ml.service.base-url=http://fastapi:8000
